// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# These endpoints are specific to Xero Files API
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/files.xro/1.0/") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Retrieves files
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of files 
    remote isolated function listFiles(ListFilesHeaders headers, *ListFilesQueries queries) returns FileList|error {
        string resourcePath = string `/Files`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Uploads a File to the inbox
    #
    # + headers - Headers to be sent with the request 
    # + payload - File content and metadata to upload to the inbox 
    # + return - File uploaded to the inbox 
    remote isolated function uploadFile(UploadFileHeaders headers, FileUploadRequest payload) returns FileObject|error {
        string resourcePath = string `/Files`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a file by a unique file ID
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + return - The requested file 
    remote isolated function getFile(string fileId, GetFileHeaders headers) returns FileObject|error {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update a file
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + payload - Updated file properties such as name and folder 
    # + return - The updated file 
    remote isolated function updateFile(string fileId, UpdateFileHeaders headers, FileObject payload) returns FileObject|error {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Deletes a specific file
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + return - Successful deletion - return response 204 no content 
    remote isolated function deleteFile(string fileId, DeleteFileHeaders headers) returns error? {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Uploads a File to a specific folder
    #
    # + folderId - pass required folder id to save file to specific folder
    # + headers - Headers to be sent with the request 
    # + payload - File content and metadata to upload to the folder 
    # + return - File uploaded to the folder 
    remote isolated function uploadFileToFolder(string folderId, UploadFileToFolderHeaders headers, FileUploadRequest payload) returns FileObject|error {
        string resourcePath = string `/Files/${getEncodedUri(folderId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves the content of a specific file
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + return - Content of the file as a byte array 
    remote isolated function getFileContent(string fileId, GetFileContentHeaders headers) returns byte[]|error {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}/Content`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieves a specific file associations
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + return - List of associations of the file 
    remote isolated function listFileAssociations(string fileId, ListFileAssociationsHeaders headers) returns Association[]|error {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}/Associations`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a new file association
    #
    # + fileId - File id for single object
    # + headers - Headers to be sent with the request 
    # + payload - Association linking the file to an object 
    # + return - The created file association 
    remote isolated function createFileAssociation(string fileId, CreateFileAssociationHeaders headers, Association payload) returns Association|error {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}/Associations`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Deletes an existing file association
    #
    # + fileId - File id for single object
    # + objectId - Object id for single object
    # + headers - Headers to be sent with the request 
    # + return - Successful deletion - return response 204 no content 
    remote isolated function deleteFileAssociation(string fileId, string objectId, DeleteFileAssociationHeaders headers) returns error? {
        string resourcePath = string `/Files/${getEncodedUri(fileId)}/Associations/${getEncodedUri(objectId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieves an association object using a unique object ID
    #
    # + objectId - Object id for single object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of associations of the object 
    remote isolated function listObjectAssociations(string objectId, ListObjectAssociationsHeaders headers, *ListObjectAssociationsQueries queries) returns Association[]|error {
        string resourcePath = string `/Associations/${getEncodedUri(objectId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieves a count of associations for a list of objects.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Association counts keyed by object ID 
    remote isolated function countAssociations(CountAssociationsHeaders headers, *CountAssociationsQueries queries) returns record {}|error {
        string resourcePath = string `/Associations/Count`;
        map<Encoding> queryParamEncoding = {"ObjectIds": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieves folders
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of folders 
    remote isolated function listFolders(ListFoldersHeaders headers, *ListFoldersQueries queries) returns Folder[]|error {
        string resourcePath = string `/Folders`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a new folder
    #
    # + headers - Headers to be sent with the request 
    # + payload - Properties of the folder to create 
    # + return - The created folder 
    remote isolated function createFolder(CreateFolderHeaders headers, Folder payload) returns Folder|error {
        string resourcePath = string `/Folders`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves specific folder by using a unique folder ID
    #
    # + folderId - Folder id for single object
    # + headers - Headers to be sent with the request 
    # + return - The requested folder 
    remote isolated function getFolder(string folderId, GetFolderHeaders headers) returns Folder|error {
        string resourcePath = string `/Folders/${getEncodedUri(folderId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Updates an existing folder
    #
    # + folderId - Folder id for single object
    # + headers - Headers to be sent with the request 
    # + payload - Updated properties of the folder 
    # + return - The updated folder 
    remote isolated function updateFolder(string folderId, UpdateFolderHeaders headers, Folder payload) returns Folder|error {
        string resourcePath = string `/Folders/${getEncodedUri(folderId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Deletes a folder
    #
    # + folderId - Folder id for single object
    # + headers - Headers to be sent with the request 
    # + return - Successful deletion - return response 204 no content 
    remote isolated function deleteFolder(string folderId, DeleteFolderHeaders headers) returns error? {
        string resourcePath = string `/Folders/${getEncodedUri(folderId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieves inbox folder
    #
    # + headers - Headers to be sent with the request 
    # + return - The inbox folder 
    remote isolated function getInbox(GetInboxHeaders headers) returns Folder|error {
        string resourcePath = string `/Inbox`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
