// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# Represents the Headers record for the operation: getFileContent
public type GetFileContentHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type FileUploadRequest record {
    string filename;
    # exact name of the file you are uploading
    string name;
    string mimeType?;
    record {byte[] fileContent; string fileName;} body;
};

public type User record {
    # First name of user
    @jsondata:Name {value: "FirstName"}
    string firstName?;
    # Last name of user
    @jsondata:Name {value: "FullName"}
    string fullName?;
    # Xero identifier
    @jsondata:Name {value: "Id"}
    string id;
    # Last name of user
    @jsondata:Name {value: "LastName"}
    string lastName?;
    # Key is Name, but returns Email address of user who created the file
    @jsondata:Name {value: "Name"}
    string name?;
};

# Represents the Headers record for the operation: uploadFileToFolder
public type UploadFileToFolderHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type Folder record {
    # The name of the folder
    @jsondata:Name {value: "Name"}
    string name;
    # The number of files in the folder
    @jsondata:Name {value: "FileCount"}
    int fileCount?;
    # The email address used to email files to the inbox. Only the inbox will have this element.
    @jsondata:Name {value: "Email"}
    string email?;
    # to indicate if the folder is the Inbox. The Inbox cannot be renamed or deleted.
    @jsondata:Name {value: "IsInbox"}
    boolean isInbox?;
    # Xero unique identifier for a folder  Files
    @jsondata:Name {value: "Id"}
    string id?;
};

# Represents the Headers record for the operation: createFolder
public type CreateFolderHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# The Object Type
public type ObjectType "Unknown"|"Accpay"|"AccPayCredit"|"AccPayPayment"|"AccRec"|"AccRecCredit"|"AccRecPayment"|"Adjustment"|"ApCreditPayment"|"ApOverPayment"|"ApOverPaymentPayment"|"ApOverPaymentSourcePayment"|"ApPrepayment"|"ApPrepaymentPayment"|"ApPrepaymentSourcePayment"|"ArCreditPayment"|"ArOverPayment"|"ArOverpaymentPayment"|"ArOverpaymentSourcePayment"|"ArPrepayment"|"ArPrepaymentPayment"|"ArPrepaymentSourcePayment"|"CashPaid"|"CashRec"|"ExpPayment"|"ManJournal"|"PurchaseOrder"|"Receipt"|"Transfer"|"Account"|"Contact"|"Business"|"Employee"|"Person"|"User"|"Org"|"FixedAsset"|"PayRun"|"PriceListItem"|"Bank"|"Current"|"Equity"|"Expense"|"Fixed"|"Liability"|"Prepayment"|"Revenue"|"Sales"|"Overheads"|"Depreciatn"|"OtherIncome"|"DirectCosts"|"Currliab"|"Termliab"|"NonCurrent"|"SalesQuote";

# Represents the Headers record for the operation: createFileAssociation
public type CreateFileAssociationHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: getFolder
public type GetFolderHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: updateFolder
public type UpdateFolderHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listFileAssociations
public type ListFileAssociationsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type Association record {
    # The date the file was created (UTC). Note- The CreatedDateUtc element is only returned when using /Associations/{ObjectId} endpoint
    @jsondata:Name {value: "CreatedDateUtc"}
    string createdDateUtc?;
    @jsondata:Name {value: "ObjectType"}
    ObjectType objectType?;
    # The identifier of the object that the file is being associated with (e.g. InvoiceID, BankTransactionID, ContactID)
    @jsondata:Name {value: "ObjectId"}
    string objectId?;
    # The size of the associated file in bytes. Note- The Size element is only returned when using /Associations/{ObjectId} endpoint
    @jsondata:Name {value: "Size"}
    int size?;
    @jsondata:Name {value: "ObjectGroup"}
    ObjectGroup objectGroup?;
    # The date the file was associated with the object (UTC). Note- The AssociationDateUtc element is only returned when using /Associations/{ObjectId} endpoint
    @jsondata:Name {value: "AssociationDateUtc"}
    string associationDateUtc?;
    # The unique identifier of the file
    @jsondata:Name {value: "FileId"}
    string fileId?;
    # Boolean flag to determines whether the file is sent with the document it is attached to on client facing communications. Note- The SendWithObject element is only returned when using /Associations/{ObjectId} endpoint
    @jsondata:Name {value: "SendWithObject"}
    boolean sendWithObject?;
    # The name of the associated file. Note- The Name element is only returned when using /Associations/{ObjectId} endpoint
    @jsondata:Name {value: "Name"}
    string name?;
};

# The Object Group that the object is in. These roughly correlate to the endpoints that can be used to retrieve the object via the core accounting API
public type ObjectGroup "Account"|"BankTransaction"|"Contact"|"CreditNote"|"Invoice"|"Item"|"ManualJournal"|"Overpayment"|"Payment"|"Prepayment"|"Quote"|"Receipt";

# Represents the Queries record for the operation: listFiles
public type ListFilesQueries record {
    # pass an optional page size value
    @constraint:Int {maxValue: 100}
    int pagesize?;
    # number of records to skip for pagination
    @constraint:Int {minValue: 1}
    int page?;
    # values to sort by
    "Name"|"Size"|"CreatedDateUTC" sort?;
    # sort direction
    "ASC"|"DESC" direction?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://identity.xero.com/connect/token";
|};

public type FileObject record {
    # Created date in UTC
    @jsondata:Name {value: "CreatedDateUtc"}
    string createdDateUtc?;
    @jsondata:Name {value: "User"}
    User user?;
    # Updated date in UTC
    @jsondata:Name {value: "UpdatedDateUtc"}
    string updatedDateUtc?;
    # Numeric value in bytes
    @jsondata:Name {value: "Size"}
    int size?;
    # File object's UUID
    @jsondata:Name {value: "Id"}
    string id?;
    # Folder relation object's UUID
    @jsondata:Name {value: "FolderId"}
    string folderId?;
    # MimeType of the file (image/png, image/jpeg, application/pdf, etc..)
    @jsondata:Name {value: "MimeType"}
    string mimeType?;
    # File Name
    @jsondata:Name {value: "Name"}
    string name?;
};

# Represents the Queries record for the operation: countAssociations
public type CountAssociationsQueries record {
    # A comma-separated list of object ids
    @http:Query {name: "ObjectIds"}
    string[] objectIds;
};

# Represents the Headers record for the operation: listFiles
public type ListFilesHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: countAssociations
public type CountAssociationsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type FileList record {
    @jsondata:Name {value: "TotalCount"}
    int totalCount?;
    @jsondata:Name {value: "PerPage"}
    int perPage?;
    @jsondata:Name {value: "Page"}
    int page?;
    @jsondata:Name {value: "Items"}
    FileObject[] items?;
};

# Represents the Headers record for the operation: getFile
public type GetFileHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: updateFile
public type UpdateFileHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: getInbox
public type GetInboxHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: deleteFile
public type DeleteFileHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: uploadFile
public type UploadFileHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listObjectAssociations
public type ListObjectAssociationsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: deleteFolder
public type DeleteFolderHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Queries record for the operation: listFolders
public type ListFoldersQueries record {
    # values to sort by
    "Name"|"Size"|"CreatedDateUTC" sort?;
};

# Represents the Headers record for the operation: deleteFileAssociation
public type DeleteFileAssociationHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listFolders
public type ListFoldersHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Queries record for the operation: listObjectAssociations
public type ListObjectAssociationsQueries record {
    # pass an optional page size value
    @constraint:Int {maxValue: 100}
    int pagesize?;
    # number of records to skip for pagination
    @constraint:Int {minValue: 1}
    int page?;
    # values to sort by
    "Name"|"Size"|"CreatedDateUtc"|"AssociationDateUtc" sort = "CreatedDateUtc";
    # direction to sort by
    "ASC"|"DESC" direction?;
};
